/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated By:JJTree&JavaCC: Do not edit this line. ELParserConstants.java */
package com.asual.summer.core.el.parser;

public interface ELParserConstants {

  int EOF = 0;
  int LITERAL_EXPRESSION = 1;
  int START_DYNAMIC_EXPRESSION = 2;
  int START_DEFERRED_EXPRESSION = 3;
  int INTEGER_LITERAL = 9;
  int FLOATING_POINT_LITERAL = 10;
  int EXPONENT = 11;
  int STRING_LITERAL = 12;
  int BADLY_ESCAPED_STRING_LITERAL = 13;
  int TRUE = 14;
  int FALSE = 15;
  int NULL = 16;
  int DOT = 17;
  int AT = 18;
  int LBRACE = 19;
  int RBRACE = 20;
  int PIPE = 21;
  int LPAREN = 22;
  int RPAREN = 23;
  int LBRACK = 24;
  int RBRACK = 25;
  int COLON = 26;
  int COMMA = 27;
  int GT0 = 28;
  int GT1 = 29;
  int LT0 = 30;
  int LT1 = 31;
  int GE0 = 32;
  int GE1 = 33;
  int LE0 = 34;
  int LE1 = 35;
  int EQ0 = 36;
  int EQ1 = 37;
  int NE0 = 38;
  int NE1 = 39;
  int NOT0 = 40;
  int NOT1 = 41;
  int AND0 = 42;
  int AND1 = 43;
  int OR0 = 44;
  int OR1 = 45;
  int EMPTY = 46;
  int INSTANCEOF = 47;
  int MULT = 48;
  int PLUS = 49;
  int MINUS = 50;
  int QUESTIONMARK = 51;
  int DIV0 = 52;
  int DIV1 = 53;
  int MOD0 = 54;
  int MOD1 = 55;
  int IDENTIFIER = 56;
  int NAMESPACE = 57;
  int FUNCTIONSUFFIX = 58;
  int IMPL_OBJ_START = 59;
  int LETTER = 60;
  int DIGIT = 61;
  int ILLEGAL_CHARACTER = 62;

  int DEFAULT = 0;
  int IN_EXPRESSION = 1;

  String[] tokenImage = {
    "<EOF>",
    "<LITERAL_EXPRESSION>",
    "\"${\"",
    "\"#{\"",
    "\"\\\\\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<BADLY_ESCAPED_STRING_LITERAL>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\".\"",
    "\"@\"",
    "\"{\"",
    "\"}\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\",\"",
    "\">\"",
    "\"gt\"",
    "\"<\"",
    "\"lt\"",
    "\">=\"",
    "\"ge\"",
    "\"<=\"",
    "\"le\"",
    "\"==\"",
    "\"eq\"",
    "\"!=\"",
    "\"ne\"",
    "\"!\"",
    "\"not\"",
    "\"&&\"",
    "\"and\"",
    "\"||\"",
    "\"or\"",
    "\"empty\"",
    "\"instanceof\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\"?\"",
    "\"/\"",
    "\"div\"",
    "\"%\"",
    "\"mod\"",
    "<IDENTIFIER>",
    "<NAMESPACE>",
    "<FUNCTIONSUFFIX>",
    "\"#\"",
    "<LETTER>",
    "<DIGIT>",
    "<ILLEGAL_CHARACTER>",
  };

}
